import React from "react";
import "../../../styles/PlayerDialog.css";

function PlayerDialog({ player }) {
  function getAge(dateString) {
    var today = new Date();
    var birthDate = new Date(dateString);
    var age = today.getFullYear() - birthDate.getFullYear();
    var m = today.getMonth() - birthDate.getMonth();
    if (m < 0 || (m === 0 && today.getDate() < birthDate.getDate())) {
      age--;
    }
    return age;
  }

  const stats = {
    id: "c8797380-9677-11ec-9193-6b32ce92fd29",
    name: "Maulers",
    market: "Pittsburgh",
    alias: "PIT",
    sr_id: "sr:competitor:882423",
    season: {
      id: "64211fe2-a136-4b6b-97ae-801275282383",
      year: 2022,
      type: "REG",
      name: "REG",
    },
    record: {
      games_played: 2,
      touchdowns: {
        pass: 2,
        rush: 0,
        total_return: 1,
        total: 3,
        fumble_return: 1,
        int_return: 0,
        kick_return: 0,
        punt_return: 0,
        other: 0,
      },
      rushing: {
        avg_yards: 3.533,
        attempts: 60,
        touchdowns: 0,
        tlost: 9,
        tlost_yards: -26,
        yards: 212,
        longest: 15,
        longest_touchdown: 0,
        redzone_attempts: 5,
        broken_tackles: 0,
        kneel_downs: 1,
        scrambles: 1,
        yards_after_contact: 0,
      },
      receiving: {
        targets: 64,
        receptions: 32,
        avg_yards: 11.406,
        yards: 365,
        touchdowns: 2,
        yards_after_catch: 76,
        longest: 37,
        longest_touchdown: 37,
        redzone_targets: 7,
        air_yards: 289,
        broken_tackles: 0,
        dropped_passes: 0,
        catchable_passes: 0,
        yards_after_contact: 0,
      },
      punts: {
        attempts: 13,
        yards: 509,
        net_yards: 455,
        blocked: 0,
        touchbacks: 1,
        inside_20: 1,
        return_yards: 29,
        avg_net_yards: 35.0,
        avg_yards: 39.154,
        longest: 50,
        hang_time: 0.0,
        avg_hang_time: 0.0,
      },
      punt_returns: {
        avg_yards: 0.5,
        returns: 2,
        yards: 1,
        longest: 1,
        touchdowns: 0,
        longest_touchdown: 0,
        faircatches: 6,
      },
      penalties: {
        penalties: 9,
        yards: 93,
      },
      passing: {
        attempts: 65,
        completions: 32,
        cmp_pct: 49.231,
        interceptions: 2,
        sack_yards: 43,
        rating: 100.4,
        touchdowns: 2,
        avg_yards: 5.615,
        sacks: 6,
        longest: 37,
        longest_touchdown: 37,
        air_yards: 289,
        redzone_attempts: 7,
        net_yards: 322,
        yards: 322,
        gross_yards: 365,
        throw_aways: 0,
        poor_throws: 0,
        defended_passes: 0,
        dropped_passes: 0,
        spikes: 0,
        blitzes: 0,
        hurries: 0,
        knockdowns: 0,
        pocket_time: 0.0,
        batted_passes: 0,
        on_target_throws: 0,
      },
      kickoffs: {
        endzone: 1,
        inside_20: 0,
        return_yards: 211,
        returned: 0,
        touchbacks: 2,
        yards: 468,
        out_of_bounds: 0,
        kickoffs: 7,
        onside_attempts: 0,
        onside_successes: 0,
        squib_kicks: 0,
      },
      kick_returns: {
        avg_yards: 12.5,
        yards: 75,
        longest: 26,
        touchdowns: 0,
        longest_touchdown: 0,
        faircatches: 1,
        returns: 6,
      },
      interceptions: {
        return_yards: 8,
        returned: 3,
        interceptions: 3,
      },
      int_returns: {
        avg_yards: 2.667,
        yards: 8,
        longest: 10,
        touchdowns: 0,
        longest_touchdown: 0,
        returns: 3,
      },
      fumbles: {
        fumbles: 1,
        lost_fumbles: 0,
        own_rec: 1,
        own_rec_yards: -1,
        opp_rec: 2,
        opp_rec_yards: 85,
        out_of_bounds: 0,
        forced_fumbles: 4,
        own_rec_tds: 0,
        opp_rec_tds: 1,
        ez_rec_tds: 0,
      },
      first_downs: {
        pass: 19,
        penalty: 3,
        rush: 8,
        total: 30,
      },
      field_goals: {
        attempts: 2,
        made: 2,
        blocked: 0,
        yards: 53,
        avg_yards: 26.5,
        longest: 28,
        missed: 0,
        pct: 100.0,
        attempts_19: 0,
        attempts_29: 2,
        attempts_39: 0,
        attempts_49: 0,
        attempts_50: 0,
        made_19: 0,
        made_29: 2,
        made_39: 0,
        made_49: 0,
        made_50: 0,
      },
      efficiency: {
        goaltogo: {
          attempts: 3,
          successes: 1,
          pct: 33.333,
        },
        redzone: {
          attempts: 5,
          successes: 1,
          pct: 20.0,
        },
        thirddown: {
          attempts: 32,
          successes: 10,
          pct: 31.25,
        },
        fourthdown: {
          attempts: 7,
          successes: 3,
          pct: 42.857,
        },
      },
      defense: {
        tackles: 77,
        assists: 49,
        combined: 126,
        sacks: 5.0,
        sack_yards: 19.0,
        interceptions: 3,
        passes_defended: 10,
        forced_fumbles: 4,
        fumble_recoveries: 2,
        qb_hits: 19,
        tloss: 10.0,
        tloss_yards: 28.0,
        safeties: 0,
        sp_tackles: 9,
        sp_assists: 3,
        sp_forced_fumbles: 0,
        sp_fumble_recoveries: 0,
        sp_blocks: 0,
        misc_tackles: 0,
        misc_assists: 0,
        misc_forced_fumbles: 0,
        misc_fumble_recoveries: 0,
        def_targets: 0,
        def_comps: 0,
        blitzes: 0,
        hurries: 0,
        knockdowns: 0,
        missed_tackles: 0,
        batted_passes: 0,
      },
      extra_points: {
        kicks: {
          attempts: 3,
          blocked: 0,
          made: 2,
          pct: 66.667,
        },
        conversions: {
          pass_attempts: 0,
          pass_successes: 0,
          rush_attempts: 0,
          rush_successes: 0,
          defense_attempts: 0,
          defense_successes: 0,
          turnover_successes: 0,
        },
        special_conversions: {
          pass_three_point_attempts: 0,
          pass_three_point_successes: 0,
          rush_three_point_attempts: 0,
          rush_three_point_successes: 0,
          defense_three_point_attempts: 0,
          defense_three_point_successes: 0,
        },
      },
    },
    opponents: {
      games_played: 2,
      touchdowns: {
        pass: 4,
        rush: 2,
        total_return: 0,
        total: 6,
        fumble_return: 0,
        int_return: 0,
        kick_return: 0,
        punt_return: 0,
        other: 0,
      },
      rushing: {
        avg_yards: 2.37,
        attempts: 46,
        touchdowns: 2,
        tlost: 9,
        tlost_yards: -22,
        yards: 109,
        longest: 11,
        longest_touchdown: 3,
        redzone_attempts: 11,
        broken_tackles: 0,
        kneel_downs: 1,
        scrambles: 4,
        yards_after_contact: 0,
      },
      receiving: {
        targets: 68,
        receptions: 46,
        avg_yards: 9.935,
        yards: 457,
        touchdowns: 4,
        yards_after_catch: 181,
        longest: 30,
        longest_touchdown: 20,
        redzone_targets: 8,
        air_yards: 276,
        broken_tackles: 0,
        dropped_passes: 0,
        catchable_passes: 0,
        yards_after_contact: 0,
      },
      punts: {
        attempts: 10,
        yards: 448,
        net_yards: 427,
        blocked: 0,
        touchbacks: 1,
        inside_20: 7,
        return_yards: 1,
        avg_net_yards: 42.7,
        avg_yards: 44.8,
        longest: 76,
        hang_time: 0.0,
        avg_hang_time: 0.0,
      },
      punt_returns: {
        avg_yards: 4.833,
        returns: 6,
        yards: 29,
        longest: 13,
        touchdowns: 0,
        longest_touchdown: 0,
        faircatches: 0,
      },
      penalties: {
        penalties: 15,
        yards: 112,
      },
      passing: {
        attempts: 68,
        completions: 46,
        cmp_pct: 67.647,
        interceptions: 3,
        sack_yards: 19,
        rating: 134.69,
        touchdowns: 4,
        avg_yards: 6.721,
        sacks: 5,
        longest: 30,
        longest_touchdown: 20,
        air_yards: 276,
        redzone_attempts: 8,
        net_yards: 438,
        yards: 438,
        gross_yards: 457,
        throw_aways: 0,
        poor_throws: 0,
        defended_passes: 0,
        dropped_passes: 0,
        spikes: 0,
        blitzes: 0,
        hurries: 0,
        knockdowns: 0,
        pocket_time: 0.0,
        batted_passes: 0,
        on_target_throws: 0,
      },
      kickoffs: {
        endzone: 0,
        inside_20: 2,
        return_yards: 100,
        returned: 0,
        touchbacks: 2,
        yards: 559,
        out_of_bounds: 0,
        kickoffs: 9,
        onside_attempts: 0,
        onside_successes: 0,
        squib_kicks: 0,
      },
      kick_returns: {
        avg_yards: 37.4,
        yards: 187,
        longest: 66,
        touchdowns: 0,
        longest_touchdown: 0,
        faircatches: 0,
        returns: 5,
      },
      interceptions: {
        return_yards: 12,
        returned: 2,
        interceptions: 2,
      },
      int_returns: {
        avg_yards: 6.0,
        yards: 12,
        longest: 12,
        touchdowns: 0,
        longest_touchdown: 0,
        returns: 2,
      },
      fumbles: {
        fumbles: 4,
        lost_fumbles: 2,
        own_rec: 2,
        own_rec_yards: 0,
        opp_rec: 0,
        opp_rec_yards: 0,
        out_of_bounds: 0,
        forced_fumbles: 0,
        own_rec_tds: 0,
        opp_rec_tds: 0,
        ez_rec_tds: 0,
      },
      first_downs: {
        pass: 22,
        penalty: 5,
        rush: 7,
        total: 34,
      },
      field_goals: {
        attempts: 2,
        made: 1,
        blocked: 0,
        yards: 23,
        avg_yards: 11.5,
        longest: 23,
        missed: 1,
        pct: 50.0,
        attempts_19: 0,
        attempts_29: 1,
        attempts_39: 1,
        attempts_49: 0,
        attempts_50: 0,
        made_19: 0,
        made_29: 1,
        made_39: 0,
        made_49: 0,
        made_50: 0,
      },
      efficiency: {
        goaltogo: {
          attempts: 5,
          successes: 5,
          pct: 100.0,
        },
        redzone: {
          attempts: 7,
          successes: 5,
          pct: 71.429,
        },
        thirddown: {
          attempts: 26,
          successes: 10,
          pct: 38.462,
        },
        fourthdown: {
          attempts: 2,
          successes: 0,
          pct: 0.0,
        },
      },
      defense: {
        tackles: 75,
        assists: 60,
        combined: 135,
        sacks: 6.0,
        sack_yards: 43.0,
        interceptions: 2,
        passes_defended: 11,
        forced_fumbles: 0,
        fumble_recoveries: 0,
        qb_hits: 9,
        tloss: 15.0,
        tloss_yards: 69.0,
        safeties: 0,
        sp_tackles: 4,
        sp_assists: 6,
        sp_forced_fumbles: 0,
        sp_fumble_recoveries: 0,
        sp_blocks: 0,
        misc_tackles: 0,
        misc_assists: 0,
        misc_forced_fumbles: 0,
        misc_fumble_recoveries: 0,
        def_targets: 0,
        def_comps: 0,
        blitzes: 0,
        hurries: 0,
        knockdowns: 0,
        missed_tackles: 0,
        batted_passes: 0,
      },
      extra_points: {
        kicks: {
          attempts: 5,
          blocked: 0,
          made: 5,
          pct: 100.0,
        },
        conversions: {
          pass_attempts: 0,
          pass_successes: 0,
          rush_attempts: 0,
          rush_successes: 0,
          defense_attempts: 0,
          defense_successes: 0,
          turnover_successes: 0,
        },
        special_conversions: {
          pass_three_point_attempts: 1,
          pass_three_point_successes: 1,
          rush_three_point_attempts: 0,
          rush_three_point_successes: 0,
          defense_three_point_attempts: 0,
          defense_three_point_successes: 0,
        },
      },
    },
    players: [
      {
        id: "06a302d0-99a6-11ec-a6e2-072ef8c4179b",
        name: "Terrell Bonds",
        jersey: "2",
        position: "CB",
        games_played: 2,
        games_started: 2,
        punt_returns: {
          returns: 2,
          yards: 1,
          avg_yards: 0.5,
          touchdowns: 0,
          longest: 1,
          faircatches: 1,
          longest_touchdown: 0,
        },
        kick_returns: {
          returns: 3,
          yards: 61,
          avg_yards: 20.333,
          touchdowns: 0,
          longest: 26,
          faircatches: 0,
          longest_touchdown: 0,
        },
        fumbles: {
          fumbles: 1,
          lost_fumbles: 0,
          own_rec: 1,
          own_rec_yards: -1,
          opp_rec: 0,
          opp_rec_yards: 0,
          out_of_bounds: 0,
          forced_fumbles: 1,
          own_rec_tds: 0,
          opp_rec_tds: 0,
          ez_rec_tds: 0,
        },
        defense: {
          tackles: 5,
          assists: 2,
          combined: 7,
          sacks: 0.0,
          sack_yards: 0.0,
          interceptions: 0,
          passes_defended: 2,
          forced_fumbles: 1,
          fumble_recoveries: 0,
          qb_hits: 1,
          tloss: 0.0,
          tloss_yards: 0.0,
          safeties: 0,
          sp_tackles: 0,
          sp_assists: 0,
          sp_forced_fumbles: 0,
          sp_fumble_recoveries: 0,
          sp_blocks: 0,
          misc_tackles: 0,
          misc_assists: 0,
          misc_forced_fumbles: 0,
          misc_fumble_recoveries: 0,
          def_targets: 0,
          def_comps: 0,
          blitzes: 0,
          hurries: 0,
          knockdowns: 0,
          missed_tackles: 0,
          batted_passes: 0,
        },
      },
      {
        id: "0f7f08b0-a56b-11ec-b024-bdae402a3fdb",
        name: "Ethan Westbrooks",
        jersey: "90",
        position: "DT",
        games_played: 1,
        games_started: 1,
        penalties: {
          penalties: 1,
          yards: 15,
        },
        defense: {
          tackles: 0,
          assists: 1,
          combined: 1,
          sacks: 0.0,
          sack_yards: 0.0,
          interceptions: 0,
          passes_defended: 0,
          forced_fumbles: 0,
          fumble_recoveries: 0,
          qb_hits: 0,
          tloss: 0.0,
          tloss_yards: 0.0,
          safeties: 0,
          sp_tackles: 0,
          sp_assists: 0,
          sp_forced_fumbles: 0,
          sp_fumble_recoveries: 0,
          sp_blocks: 0,
          misc_tackles: 0,
          misc_assists: 0,
          misc_forced_fumbles: 0,
          misc_fumble_recoveries: 0,
          def_targets: 0,
          def_comps: 0,
          blitzes: 0,
          hurries: 0,
          knockdowns: 0,
          missed_tackles: 0,
          batted_passes: 0,
        },
      },
      {
        id: "1b363bd0-99a7-11ec-9588-2d3ae1c75954",
        name: "Branden Mack",
        jersey: "1",
        position: "WR",
        games_played: 1,
        games_started: 0,
        receiving: {
          receptions: 1,
          targets: 3,
          yards: 12,
          avg_yards: 12.0,
          longest: 12,
          touchdowns: 0,
          longest_touchdown: 0,
          yards_after_catch: 2,
          redzone_targets: 1,
          air_yards: 10,
          broken_tackles: 0,
          dropped_passes: 0,
          catchable_passes: 0,
          yards_after_contact: 0,
        },
        defense: {
          tackles: 0,
          assists: 0,
          combined: 0,
          sacks: 0.0,
          sack_yards: 0.0,
          interceptions: 0,
          passes_defended: 0,
          forced_fumbles: 0,
          fumble_recoveries: 0,
          qb_hits: 0,
          tloss: 0.0,
          tloss_yards: 0.0,
          safeties: 0,
          sp_tackles: 1,
          sp_assists: 1,
          sp_forced_fumbles: 0,
          sp_fumble_recoveries: 0,
          sp_blocks: 0,
          misc_tackles: 0,
          misc_assists: 0,
          misc_forced_fumbles: 0,
          misc_fumble_recoveries: 0,
          def_targets: 0,
          def_comps: 0,
          blitzes: 0,
          hurries: 0,
          knockdowns: 0,
          missed_tackles: 0,
          batted_passes: 0,
        },
      },
      {
        id: "1bc75da0-99ba-11ec-86dc-ff0add1e628b",
        name: "Boogie Roberts",
        jersey: "91",
        position: "DT",
        games_played: 2,
        games_started: 1,
        penalties: {
          penalties: 1,
          yards: 11,
        },
        defense: {
          tackles: 2,
          assists: 2,
          combined: 4,
          sacks: 0.0,
          sack_yards: 0.0,
          interceptions: 0,
          passes_defended: 0,
          forced_fumbles: 0,
          fumble_recoveries: 0,
          qb_hits: 2,
          tloss: 0.0,
          tloss_yards: 0.0,
          safeties: 0,
          sp_tackles: 0,
          sp_assists: 0,
          sp_forced_fumbles: 0,
          sp_fumble_recoveries: 0,
          sp_blocks: 0,
          misc_tackles: 0,
          misc_assists: 0,
          misc_forced_fumbles: 0,
          misc_fumble_recoveries: 0,
          def_targets: 0,
          def_comps: 0,
          blitzes: 0,
          hurries: 0,
          knockdowns: 0,
          missed_tackles: 0,
          batted_passes: 0,
        },
      },
      {
        id: "1c4bbac0-99b8-11ec-86dc-ff0add1e628b",
        name: "DelVon Hardaway",
        jersey: "7",
        position: "WR",
        games_played: 2,
        games_started: 0,
        receiving: {
          receptions: 5,
          targets: 13,
          yards: 70,
          avg_yards: 14.0,
          longest: 35,
          touchdowns: 0,
          longest_touchdown: 0,
          yards_after_catch: 14,
          redzone_targets: 0,
          air_yards: 56,
          broken_tackles: 0,
          dropped_passes: 0,
          catchable_passes: 0,
          yards_after_contact: 0,
        },
      },
      {
        id: "1c7ff4b0-99b9-11ec-86dc-ff0add1e628b",
        name: "E.J. Ejiya",
        jersey: "44",
        position: "LB",
        games_played: 2,
        games_started: 2,
        defense: {
          tackles: 4,
          assists: 9,
          combined: 13,
          sacks: 0.0,
          sack_yards: 0.0,
          interceptions: 0,
          passes_defended: 1,
          forced_fumbles: 0,
          fumble_recoveries: 0,
          qb_hits: 1,
          tloss: 0.0,
          tloss_yards: 1.0,
          safeties: 0,
          sp_tackles: 0,
          sp_assists: 0,
          sp_forced_fumbles: 0,
          sp_fumble_recoveries: 0,
          sp_blocks: 0,
          misc_tackles: 0,
          misc_assists: 0,
          misc_forced_fumbles: 0,
          misc_fumble_recoveries: 0,
          def_targets: 0,
          def_comps: 0,
          blitzes: 0,
          hurries: 0,
          knockdowns: 0,
          missed_tackles: 0,
          batted_passes: 0,
        },
      },
      {
        id: "2ad97070-99bb-11ec-86dc-ff0add1e628b",
        name: "Malcolm Howard",
        jersey: "6",
        position: "OLB",
        games_played: 1,
        games_started: 0,
        defense: {
          tackles: 0,
          assists: 0,
          combined: 0,
          sacks: 0.0,
          sack_yards: 0.0,
          interceptions: 0,
          passes_defended: 0,
          forced_fumbles: 0,
          fumble_recoveries: 0,
          qb_hits: 0,
          tloss: 0.0,
          tloss_yards: 0.0,
          safeties: 0,
          sp_tackles: 1,
          sp_assists: 0,
          sp_forced_fumbles: 0,
          sp_fumble_recoveries: 0,
          sp_blocks: 0,
          misc_tackles: 0,
          misc_assists: 0,
          misc_forced_fumbles: 0,
          misc_fumble_recoveries: 0,
          def_targets: 0,
          def_comps: 0,
          blitzes: 0,
          hurries: 0,
          knockdowns: 0,
          missed_tackles: 0,
          batted_passes: 0,
        },
      },
      {
        id: "2b71f670-a56d-11ec-b024-bdae402a3fdb",
        name: "Malcolm Elmore",
        jersey: "20",
        position: "SAF",
        games_played: 2,
        games_started: 1,
        defense: {
          tackles: 1,
          assists: 1,
          combined: 2,
          sacks: 0.0,
          sack_yards: 0.0,
          interceptions: 0,
          passes_defended: 0,
          forced_fumbles: 0,
          fumble_recoveries: 0,
          qb_hits: 0,
          tloss: 0.0,
          tloss_yards: 0.0,
          safeties: 0,
          sp_tackles: 0,
          sp_assists: 0,
          sp_forced_fumbles: 0,
          sp_fumble_recoveries: 0,
          sp_blocks: 0,
          misc_tackles: 0,
          misc_assists: 0,
          misc_forced_fumbles: 0,
          misc_fumble_recoveries: 0,
          def_targets: 0,
          def_comps: 0,
          blitzes: 0,
          hurries: 0,
          knockdowns: 0,
          missed_tackles: 0,
          batted_passes: 0,
        },
      },
      {
        id: "2c418030-99a0-11ec-9c60-e7842fa378d2",
        name: "Carlo Kemp",
        jersey: "99",
        position: "DE",
        games_played: 2,
        games_started: 2,
        fumbles: {
          fumbles: 0,
          lost_fumbles: 0,
          own_rec: 0,
          own_rec_yards: 0,
          opp_rec: 1,
          opp_rec_yards: 6,
          out_of_bounds: 0,
          forced_fumbles: 1,
          own_rec_tds: 0,
          opp_rec_tds: 0,
          ez_rec_tds: 0,
        },
        defense: {
          tackles: 9,
          assists: 5,
          combined: 14,
          sacks: 2.5,
          sack_yards: 9.0,
          interceptions: 0,
          passes_defended: 0,
          forced_fumbles: 1,
          fumble_recoveries: 1,
          qb_hits: 5,
          tloss: 3.0,
          tloss_yards: 7.0,
          safeties: 0,
          sp_tackles: 0,
          sp_assists: 0,
          sp_forced_fumbles: 0,
          sp_fumble_recoveries: 0,
          sp_blocks: 0,
          misc_tackles: 0,
          misc_assists: 0,
          misc_forced_fumbles: 0,
          misc_fumble_recoveries: 0,
          def_targets: 0,
          def_comps: 0,
          blitzes: 0,
          hurries: 0,
          knockdowns: 0,
          missed_tackles: 0,
          batted_passes: 0,
        },
      },
      {
        id: "31ba6ed0-a56e-11ec-b024-bdae402a3fdb",
        name: "Ramiz Ahmed",
        jersey: "16",
        position: "K",
        games_played: 2,
        games_started: 0,
        kickoffs: {
          kickoffs: 7,
          endzone: 1,
          inside_20: 0,
          return_yards: 211,
          touchbacks: 2,
          yards: 468,
          out_of_bounds: 0,
          onside_attempts: 0,
          onside_successes: 0,
          squib_kicks: 0,
        },
        field_goals: {
          attempts: 2,
          made: 2,
          blocked: 0,
          yards: 53,
          avg_yards: 26.5,
          longest: 28,
          missed: 0,
          pct: 100.0,
          attempts_19: 0,
          attempts_29: 2,
          attempts_39: 0,
          attempts_49: 0,
          attempts_50: 0,
          made_19: 0,
          made_29: 2,
          made_39: 0,
          made_49: 0,
          made_50: 0,
        },
        extra_points: {
          attempts: 3,
          made: 2,
          blocked: 0,
          missed: 1,
          pct: 66.667,
        },
        defense: {
          tackles: 0,
          assists: 0,
          combined: 0,
          sacks: 0.0,
          sack_yards: 0.0,
          interceptions: 0,
          passes_defended: 0,
          forced_fumbles: 0,
          fumble_recoveries: 0,
          qb_hits: 0,
          tloss: 0.0,
          tloss_yards: 0.0,
          safeties: 0,
          sp_tackles: 2,
          sp_assists: 0,
          sp_forced_fumbles: 0,
          sp_fumble_recoveries: 0,
          sp_blocks: 0,
          misc_tackles: 0,
          misc_assists: 0,
          misc_forced_fumbles: 0,
          misc_fumble_recoveries: 0,
          def_targets: 0,
          def_comps: 0,
          blitzes: 0,
          hurries: 0,
          knockdowns: 0,
          missed_tackles: 0,
          batted_passes: 0,
        },
      },
      {
        id: "34506e70-99a6-11ec-a6e2-072ef8c4179b",
        name: "Prince Robinson",
        jersey: "23",
        position: "CB",
        games_played: 1,
        games_started: 0,
        defense: {
          tackles: 1,
          assists: 1,
          combined: 2,
          sacks: 0.0,
          sack_yards: 0.0,
          interceptions: 0,
          passes_defended: 0,
          forced_fumbles: 0,
          fumble_recoveries: 0,
          qb_hits: 0,
          tloss: 0.0,
          tloss_yards: 0.0,
          safeties: 0,
          sp_tackles: 0,
          sp_assists: 0,
          sp_forced_fumbles: 0,
          sp_fumble_recoveries: 0,
          sp_blocks: 0,
          misc_tackles: 0,
          misc_assists: 0,
          misc_forced_fumbles: 0,
          misc_fumble_recoveries: 0,
          def_targets: 0,
          def_comps: 0,
          blitzes: 0,
          hurries: 0,
          knockdowns: 0,
          missed_tackles: 0,
          batted_passes: 0,
        },
      },
      {
        id: "35af7220-99ba-11ec-86dc-ff0add1e628b",
        name: "Jeremiah Pharms Jr.",
        jersey: "92",
        position: "DT",
        games_played: 2,
        games_started: 0,
        defense: {
          tackles: 1,
          assists: 3,
          combined: 4,
          sacks: 0.5,
          sack_yards: 2.0,
          interceptions: 0,
          passes_defended: 0,
          forced_fumbles: 0,
          fumble_recoveries: 0,
          qb_hits: 2,
          tloss: 0.0,
          tloss_yards: 0.0,
          safeties: 0,
          sp_tackles: 0,
          sp_assists: 0,
          sp_forced_fumbles: 0,
          sp_fumble_recoveries: 0,
          sp_blocks: 0,
          misc_tackles: 0,
          misc_assists: 0,
          misc_forced_fumbles: 0,
          misc_fumble_recoveries: 0,
          def_targets: 0,
          def_comps: 0,
          blitzes: 0,
          hurries: 0,
          knockdowns: 0,
          missed_tackles: 0,
          batted_passes: 0,
        },
      },
      {
        id: "40a32be0-a568-11ec-b024-bdae402a3fdb",
        name: "Justin Evans",
        jersey: "51",
        position: "OL",
        games_played: 2,
        games_started: 2,
        penalties: {
          penalties: 1,
          yards: 13,
        },
      },
      {
        id: "4734fd50-99b8-11ec-86dc-ff0add1e628b",
        name: "Tre Walker",
        jersey: "89",
        position: "WR",
        games_played: 1,
        games_started: 0,
        receiving: {
          receptions: 3,
          targets: 7,
          yards: 27,
          avg_yards: 9.0,
          longest: 13,
          touchdowns: 0,
          longest_touchdown: 0,
          yards_after_catch: 3,
          redzone_targets: 0,
          air_yards: 24,
          broken_tackles: 0,
          dropped_passes: 0,
          catchable_passes: 0,
          yards_after_contact: 0,
        },
        kick_returns: {
          returns: 1,
          yards: 9,
          avg_yards: 9.0,
          touchdowns: 0,
          longest: 9,
          faircatches: 0,
          longest_touchdown: 0,
        },
        defense: {
          tackles: 2,
          assists: 0,
          combined: 2,
          sacks: 0.0,
          sack_yards: 0.0,
          interceptions: 0,
          passes_defended: 0,
          forced_fumbles: 0,
          fumble_recoveries: 0,
          qb_hits: 0,
          tloss: 0.0,
          tloss_yards: 0.0,
          safeties: 0,
          sp_tackles: 0,
          sp_assists: 0,
          sp_forced_fumbles: 0,
          sp_fumble_recoveries: 0,
          sp_blocks: 0,
          misc_tackles: 0,
          misc_assists: 0,
          misc_forced_fumbles: 0,
          misc_fumble_recoveries: 0,
          def_targets: 0,
          def_comps: 0,
          blitzes: 0,
          hurries: 0,
          knockdowns: 0,
          missed_tackles: 0,
          batted_passes: 0,
        },
      },
      {
        id: "49056470-99a0-11ec-9c60-e7842fa378d2",
        name: "Nasir Player",
        jersey: "95",
        position: "DE",
        games_played: 1,
        games_started: 0,
        kick_returns: {
          returns: 0,
          yards: 0,
          avg_yards: 0.0,
          touchdowns: 0,
          longest: 0,
          faircatches: 1,
          longest_touchdown: 0,
        },
        defense: {
          tackles: 1,
          assists: 1,
          combined: 2,
          sacks: 0.0,
          sack_yards: 0.0,
          interceptions: 0,
          passes_defended: 0,
          forced_fumbles: 0,
          fumble_recoveries: 0,
          qb_hits: 0,
          tloss: 0.0,
          tloss_yards: 0.0,
          safeties: 0,
          sp_tackles: 1,
          sp_assists: 0,
          sp_forced_fumbles: 0,
          sp_fumble_recoveries: 0,
          sp_blocks: 0,
          misc_tackles: 0,
          misc_assists: 0,
          misc_forced_fumbles: 0,
          misc_fumble_recoveries: 0,
          def_targets: 0,
          def_comps: 0,
          blitzes: 0,
          hurries: 0,
          knockdowns: 0,
          missed_tackles: 0,
          batted_passes: 0,
        },
      },
      {
        id: "4d503de0-a56f-11ec-b024-bdae402a3fdb",
        name: "Darrius Moragne",
        jersey: "97",
        position: "DT",
        games_played: 2,
        games_started: 2,
        penalties: {
          penalties: 2,
          yards: 30,
        },
        defense: {
          tackles: 5,
          assists: 3,
          combined: 8,
          sacks: 0.5,
          sack_yards: 2.5,
          interceptions: 0,
          passes_defended: 0,
          forced_fumbles: 0,
          fumble_recoveries: 0,
          qb_hits: 2,
          tloss: 2.0,
          tloss_yards: 4.0,
          safeties: 0,
          sp_tackles: 0,
          sp_assists: 0,
          sp_forced_fumbles: 0,
          sp_fumble_recoveries: 0,
          sp_blocks: 0,
          misc_tackles: 0,
          misc_assists: 0,
          misc_forced_fumbles: 0,
          misc_fumble_recoveries: 0,
          def_targets: 0,
          def_comps: 0,
          blitzes: 0,
          hurries: 0,
          knockdowns: 0,
          missed_tackles: 0,
          batted_passes: 0,
        },
      },
      {
        id: "51cbfd60-99bb-11ec-86dc-ff0add1e628b",
        name: "Kyahva Tezino",
        jersey: "31",
        position: "OLB",
        games_played: 2,
        games_started: 2,
        int_returns: {
          returns: 1,
          yards: -2,
          avg_yards: -2.0,
          touchdowns: 0,
          longest: -2,
          longest_touchdown: 0,
        },
        fumbles: {
          fumbles: 0,
          lost_fumbles: 0,
          own_rec: 0,
          own_rec_yards: 0,
          opp_rec: 0,
          opp_rec_yards: 0,
          out_of_bounds: 0,
          forced_fumbles: 1,
          own_rec_tds: 0,
          opp_rec_tds: 0,
          ez_rec_tds: 0,
        },
        defense: {
          tackles: 14,
          assists: 7,
          combined: 21,
          sacks: 0.5,
          sack_yards: 2.5,
          interceptions: 1,
          passes_defended: 3,
          forced_fumbles: 1,
          fumble_recoveries: 0,
          qb_hits: 3,
          tloss: 2.0,
          tloss_yards: 8.0,
          safeties: 0,
          sp_tackles: 0,
          sp_assists: 1,
          sp_forced_fumbles: 0,
          sp_fumble_recoveries: 0,
          sp_blocks: 0,
          misc_tackles: 0,
          misc_assists: 0,
          misc_forced_fumbles: 0,
          misc_fumble_recoveries: 0,
          def_targets: 0,
          def_comps: 0,
          blitzes: 0,
          hurries: 0,
          knockdowns: 0,
          missed_tackles: 0,
          batted_passes: 0,
        },
      },
      {
        id: "59d90b20-99a6-11ec-a6e2-072ef8c4179b",
        name: "Jaylon McClain-Sapp",
        jersey: "24",
        position: "CB",
        games_played: 2,
        games_started: 2,
        penalties: {
          penalties: 2,
          yards: 11,
        },
        int_returns: {
          returns: 1,
          yards: 0,
          avg_yards: 0.0,
          touchdowns: 0,
          longest: 0,
          longest_touchdown: 0,
        },
        fumbles: {
          fumbles: 0,
          lost_fumbles: 0,
          own_rec: 0,
          own_rec_yards: 0,
          opp_rec: 1,
          opp_rec_yards: 79,
          out_of_bounds: 0,
          forced_fumbles: 0,
          own_rec_tds: 0,
          opp_rec_tds: 1,
          ez_rec_tds: 0,
        },
        defense: {
          tackles: 4,
          assists: 3,
          combined: 7,
          sacks: 0.0,
          sack_yards: 0.0,
          interceptions: 1,
          passes_defended: 1,
          forced_fumbles: 0,
          fumble_recoveries: 1,
          qb_hits: 0,
          tloss: 0.0,
          tloss_yards: 1.0,
          safeties: 0,
          sp_tackles: 0,
          sp_assists: 0,
          sp_forced_fumbles: 0,
          sp_fumble_recoveries: 0,
          sp_blocks: 0,
          misc_tackles: 0,
          misc_assists: 0,
          misc_forced_fumbles: 0,
          misc_fumble_recoveries: 0,
          def_targets: 0,
          def_comps: 0,
          blitzes: 0,
          hurries: 0,
          knockdowns: 0,
          missed_tackles: 0,
          batted_passes: 0,
        },
      },
      {
        id: "5fa2b160-99b9-11ec-86dc-ff0add1e628b",
        name: "Vadal Alexander",
        jersey: "78",
        position: "OL",
        games_played: 2,
        games_started: 2,
      },
      {
        id: "69c4f370-99b8-11ec-86dc-ff0add1e628b",
        name: "Arnold Tarpley III",
        jersey: "21",
        position: "SAF",
        games_played: 2,
        games_started: 2,
        int_returns: {
          returns: 1,
          yards: 10,
          avg_yards: 10.0,
          touchdowns: 0,
          longest: 10,
          longest_touchdown: 0,
        },
        defense: {
          tackles: 8,
          assists: 3,
          combined: 11,
          sacks: 0.0,
          sack_yards: 0.0,
          interceptions: 1,
          passes_defended: 2,
          forced_fumbles: 0,
          fumble_recoveries: 0,
          qb_hits: 0,
          tloss: 0.0,
          tloss_yards: 0.0,
          safeties: 0,
          sp_tackles: 0,
          sp_assists: 0,
          sp_forced_fumbles: 0,
          sp_fumble_recoveries: 0,
          sp_blocks: 0,
          misc_tackles: 0,
          misc_assists: 0,
          misc_forced_fumbles: 0,
          misc_fumble_recoveries: 0,
          def_targets: 0,
          def_comps: 0,
          blitzes: 0,
          hurries: 0,
          knockdowns: 0,
          missed_tackles: 0,
          batted_passes: 0,
        },
      },
      {
        id: "74484670-99a5-11ec-a6e2-072ef8c4179b",
        name: "Isaiah Battle",
        jersey: "0",
        position: "T",
        games_played: 0,
        games_started: 0,
      },
      {
        id: "754aba60-a56e-11ec-b024-bdae402a3fdb",
        name: "Hunter Thedford",
        jersey: "85",
        position: "TE",
        games_played: 2,
        games_started: 1,
        receiving: {
          receptions: 2,
          targets: 6,
          yards: 10,
          avg_yards: 5.0,
          longest: 5,
          touchdowns: 1,
          longest_touchdown: 5,
          yards_after_catch: 0,
          redzone_targets: 3,
          air_yards: 10,
          broken_tackles: 0,
          dropped_passes: 0,
          catchable_passes: 0,
          yards_after_contact: 0,
        },
      },
      {
        id: "77adb230-b478-11ec-8cfb-57723febc64f",
        name: "Mikey Daniel",
        jersey: "38",
        position: "FB",
        games_played: 2,
        games_started: 1,
        receiving: {
          receptions: 2,
          targets: 4,
          yards: 13,
          avg_yards: 6.5,
          longest: 7,
          touchdowns: 0,
          longest_touchdown: 0,
          yards_after_catch: 12,
          redzone_targets: 0,
          air_yards: 1,
          broken_tackles: 0,
          dropped_passes: 0,
          catchable_passes: 0,
          yards_after_contact: 0,
        },
      },
      {
        id: "78649a00-a56d-11ec-b024-bdae402a3fdb",
        name: "Abdul Beecham",
        jersey: "62",
        position: "OL",
        games_played: 2,
        games_started: 2,
      },
      {
        id: "7fa51970-99a6-11ec-a6e2-072ef8c4179b",
        name: "Josh Love",
        jersey: "12",
        position: "QB",
        games_played: 2,
        games_started: 2,
        rushing: {
          avg_yards: 5.5,
          attempts: 2,
          touchdowns: 0,
          yards: 11,
          longest: 12,
          longest_touchdown: 0,
          redzone_attempts: 0,
          tlost: 0,
          tlost_yards: 0,
          broken_tackles: 0,
          kneel_downs: 1,
          scrambles: 1,
          yards_after_contact: 0,
        },
        passing: {
          attempts: 54,
          completions: 30,
          cmp_pct: 55.556,
          yards: 357,
          avg_yards: 6.611,
          sacks: 5,
          sack_yards: 31,
          touchdowns: 2,
          longest: 37,
          interceptions: 2,
          rating: 115.9,
          longest_touchdown: 37,
          air_yards: 283,
          redzone_attempts: 7,
          gross_yards: 357,
          throw_aways: 0,
          poor_throws: 0,
          defended_passes: 0,
          dropped_passes: 0,
          spikes: 0,
          blitzes: 0,
          hurries: 0,
          knockdowns: 0,
          pocket_time: 0.0,
          avg_pocket_time: 0.0,
          net_yards: 326,
          batted_passes: 0,
          on_target_throws: 0,
        },
      },
      {
        id: "806b4480-a56b-11ec-b024-bdae402a3fdb",
        name: "Keith Gipson Jr.",
        jersey: "11",
        position: "CB",
        games_played: 1,
        games_started: 0,
        defense: {
          tackles: 6,
          assists: 0,
          combined: 6,
          sacks: 0.0,
          sack_yards: 0.0,
          interceptions: 0,
          passes_defended: 1,
          forced_fumbles: 0,
          fumble_recoveries: 0,
          qb_hits: 0,
          tloss: 0.0,
          tloss_yards: 0.0,
          safeties: 0,
          sp_tackles: 0,
          sp_assists: 0,
          sp_forced_fumbles: 0,
          sp_fumble_recoveries: 0,
          sp_blocks: 0,
          misc_tackles: 0,
          misc_assists: 0,
          misc_forced_fumbles: 0,
          misc_fumble_recoveries: 0,
          def_targets: 0,
          def_comps: 0,
          blitzes: 0,
          hurries: 0,
          knockdowns: 0,
          missed_tackles: 0,
          batted_passes: 0,
        },
      },
      {
        id: "89fd84b0-99bb-11ec-86dc-ff0add1e628b",
        name: "Blair Brown",
        jersey: "52",
        position: "LB",
        games_played: 0,
        games_started: 0,
      },
      {
        id: "911ab990-99b9-11ec-86dc-ff0add1e628b",
        name: "Jon Dietzen",
        jersey: "67",
        position: "G",
        games_played: 2,
        games_started: 2,
      },
      {
        id: "98620450-99ba-11ec-86dc-ff0add1e628b",
        name: "Garrett Groshek",
        jersey: "37",
        position: "RB",
        games_played: 2,
        games_started: 2,
        rushing: {
          avg_yards: 3.882,
          attempts: 34,
          touchdowns: 0,
          yards: 132,
          longest: 15,
          longest_touchdown: 0,
          redzone_attempts: 1,
          tlost: 3,
          tlost_yards: -12,
          broken_tackles: 0,
          kneel_downs: 0,
          scrambles: 0,
          yards_after_contact: 0,
        },
        receiving: {
          receptions: 1,
          targets: 1,
          yards: 5,
          avg_yards: 5.0,
          longest: 5,
          touchdowns: 0,
          longest_touchdown: 0,
          yards_after_catch: 11,
          redzone_targets: 0,
          air_yards: -6,
          broken_tackles: 0,
          dropped_passes: 0,
          catchable_passes: 0,
          yards_after_contact: 0,
        },
        defense: {
          tackles: 0,
          assists: 0,
          combined: 0,
          sacks: 0.0,
          sack_yards: 0.0,
          interceptions: 0,
          passes_defended: 0,
          forced_fumbles: 0,
          fumble_recoveries: 0,
          qb_hits: 0,
          tloss: 0.0,
          tloss_yards: 0.0,
          safeties: 0,
          sp_tackles: 1,
          sp_assists: 0,
          sp_forced_fumbles: 0,
          sp_fumble_recoveries: 0,
          sp_blocks: 0,
          misc_tackles: 0,
          misc_assists: 0,
          misc_forced_fumbles: 0,
          misc_fumble_recoveries: 0,
          def_targets: 0,
          def_comps: 0,
          blitzes: 0,
          hurries: 0,
          knockdowns: 0,
          missed_tackles: 0,
          batted_passes: 0,
        },
      },
      {
        id: "a10a9950-99a6-11ec-a6e2-072ef8c4179b",
        name: "Jeffrey Thomas",
        jersey: "10",
        position: "WR",
        games_played: 1,
        games_started: 0,
        receiving: {
          receptions: 4,
          targets: 8,
          yards: 43,
          avg_yards: 10.75,
          longest: 32,
          touchdowns: 0,
          longest_touchdown: 0,
          yards_after_catch: 1,
          redzone_targets: 2,
          air_yards: 42,
          broken_tackles: 0,
          dropped_passes: 0,
          catchable_passes: 0,
          yards_after_contact: 0,
        },
        punt_returns: {
          returns: 0,
          yards: 0,
          avg_yards: 0.0,
          touchdowns: 0,
          longest: 0,
          faircatches: 4,
          longest_touchdown: 0,
        },
        kick_returns: {
          returns: 2,
          yards: 5,
          avg_yards: 2.5,
          touchdowns: 0,
          longest: 6,
          faircatches: 0,
          longest_touchdown: 0,
        },
      },
      {
        id: "a4a357d0-99a3-11ec-a6e2-072ef8c4179b",
        name: "Chidi Okeke",
        jersey: "68",
        position: "T",
        games_played: 2,
        games_started: 2,
      },
      {
        id: "a7a5b070-99a5-11ec-a6e2-072ef8c4179b",
        name: "Charles Baldwin",
        jersey: "72",
        position: "T",
        games_played: 1,
        games_started: 1,
      },
      {
        id: "ab694620-99bb-11ec-86dc-ff0add1e628b",
        name: "Matt Seybert",
        jersey: "17",
        position: "TE",
        games_played: 2,
        games_started: 2,
        receiving: {
          receptions: 2,
          targets: 4,
          yards: 15,
          avg_yards: 7.5,
          longest: 9,
          touchdowns: 0,
          longest_touchdown: 0,
          yards_after_catch: 2,
          redzone_targets: 0,
          air_yards: 13,
          broken_tackles: 0,
          dropped_passes: 0,
          catchable_passes: 0,
          yards_after_contact: 0,
        },
      },
      {
        id: "acae2990-99b8-11ec-86dc-ff0add1e628b",
        name: "Bryce Torneden",
        jersey: "22",
        position: "SAF",
        games_played: 2,
        games_started: 2,
        penalties: {
          penalties: 1,
          yards: 10,
        },
        defense: {
          tackles: 9,
          assists: 4,
          combined: 13,
          sacks: 0.0,
          sack_yards: 0.0,
          interceptions: 0,
          passes_defended: 0,
          forced_fumbles: 0,
          fumble_recoveries: 0,
          qb_hits: 1,
          tloss: 1.0,
          tloss_yards: 2.0,
          safeties: 0,
          sp_tackles: 0,
          sp_assists: 0,
          sp_forced_fumbles: 0,
          sp_fumble_recoveries: 0,
          sp_blocks: 0,
          misc_tackles: 0,
          misc_assists: 0,
          misc_forced_fumbles: 0,
          misc_fumble_recoveries: 0,
          def_targets: 0,
          def_comps: 0,
          blitzes: 0,
          hurries: 0,
          knockdowns: 0,
          missed_tackles: 0,
          batted_passes: 0,
        },
      },
      {
        id: "be175af0-a56e-11ec-b024-bdae402a3fdb",
        name: "Max Duffy",
        jersey: "18",
        position: "P",
        games_played: 2,
        games_started: 0,
        punts: {
          attempts: 13,
          yards: 509,
          avg_yards: 39.154,
          blocked: 0,
          longest: 50,
          touchbacks: 1,
          inside_20: 1,
          avg_net_yards: 35.0,
          return_yards: 29,
          net_yards: 455,
          hang_time: 0.0,
          avg_hang_time: 0.0,
        },
      },
      {
        id: "c137cf00-99a0-11ec-a638-bf40e322d104",
        name: "Eric Assoua",
        jersey: "56",
        position: "DE",
        games_played: 1,
        games_started: 0,
        fumbles: {
          fumbles: 0,
          lost_fumbles: 0,
          own_rec: 0,
          own_rec_yards: 0,
          opp_rec: 0,
          opp_rec_yards: 0,
          out_of_bounds: 0,
          forced_fumbles: 1,
          own_rec_tds: 0,
          opp_rec_tds: 0,
          ez_rec_tds: 0,
        },
        defense: {
          tackles: 2,
          assists: 0,
          combined: 2,
          sacks: 1.0,
          sack_yards: 3.0,
          interceptions: 0,
          passes_defended: 0,
          forced_fumbles: 1,
          fumble_recoveries: 0,
          qb_hits: 2,
          tloss: 0.0,
          tloss_yards: 0.0,
          safeties: 0,
          sp_tackles: 0,
          sp_assists: 0,
          sp_forced_fumbles: 0,
          sp_fumble_recoveries: 0,
          sp_blocks: 0,
          misc_tackles: 0,
          misc_assists: 0,
          misc_forced_fumbles: 0,
          misc_fumble_recoveries: 0,
          def_targets: 0,
          def_comps: 0,
          blitzes: 0,
          hurries: 0,
          knockdowns: 0,
          missed_tackles: 0,
          batted_passes: 0,
        },
      },
      {
        id: "cb0eed90-99bb-11ec-86dc-ff0add1e628b",
        name: "Mitchell Fraboni",
        jersey: "48",
        position: "LS",
        games_played: 2,
        games_started: 0,
        defense: {
          tackles: 0,
          assists: 0,
          combined: 0,
          sacks: 0.0,
          sack_yards: 0.0,
          interceptions: 0,
          passes_defended: 0,
          forced_fumbles: 0,
          fumble_recoveries: 0,
          qb_hits: 0,
          tloss: 0.0,
          tloss_yards: 0.0,
          safeties: 0,
          sp_tackles: 1,
          sp_assists: 0,
          sp_forced_fumbles: 0,
          sp_fumble_recoveries: 0,
          sp_blocks: 0,
          misc_tackles: 0,
          misc_assists: 0,
          misc_forced_fumbles: 0,
          misc_fumble_recoveries: 0,
          def_targets: 0,
          def_comps: 0,
          blitzes: 0,
          hurries: 0,
          knockdowns: 0,
          missed_tackles: 0,
          batted_passes: 0,
        },
      },
      {
        id: "cfdd7780-99b9-11ec-86dc-ff0add1e628b",
        name: "Olive Sagapolu",
        jersey: "94",
        position: "DT",
        games_played: 2,
        games_started: 2,
        defense: {
          tackles: 2,
          assists: 2,
          combined: 4,
          sacks: 0.0,
          sack_yards: 0.0,
          interceptions: 0,
          passes_defended: 0,
          forced_fumbles: 0,
          fumble_recoveries: 0,
          qb_hits: 0,
          tloss: 2.0,
          tloss_yards: 5.0,
          safeties: 0,
          sp_tackles: 0,
          sp_assists: 0,
          sp_forced_fumbles: 0,
          sp_fumble_recoveries: 0,
          sp_blocks: 0,
          misc_tackles: 0,
          misc_assists: 0,
          misc_forced_fumbles: 0,
          misc_fumble_recoveries: 0,
          def_targets: 0,
          def_comps: 0,
          blitzes: 0,
          hurries: 0,
          knockdowns: 0,
          missed_tackles: 0,
          batted_passes: 0,
        },
      },
      {
        id: "d8e8d380-af7e-11ec-ab5e-c17af5eb9560",
        name: "Madre London",
        jersey: "9",
        position: "RB",
        games_played: 2,
        games_started: 0,
        rushing: {
          avg_yards: 2.875,
          attempts: 24,
          touchdowns: 0,
          yards: 69,
          longest: 10,
          longest_touchdown: 0,
          redzone_attempts: 4,
          tlost: 6,
          tlost_yards: -14,
          broken_tackles: 0,
          kneel_downs: 0,
          scrambles: 0,
          yards_after_contact: 0,
        },
        receiving: {
          receptions: 2,
          targets: 2,
          yards: 11,
          avg_yards: 5.5,
          longest: 10,
          touchdowns: 0,
          longest_touchdown: 0,
          yards_after_catch: 16,
          redzone_targets: 0,
          air_yards: -5,
          broken_tackles: 0,
          dropped_passes: 0,
          catchable_passes: 0,
          yards_after_contact: 0,
        },
      },
      {
        id: "da348e90-999f-11ec-9c60-e7842fa378d2",
        name: "Kyle Lauletta",
        jersey: "5",
        position: "QB",
        games_played: 1,
        games_started: 0,
        penalties: {
          penalties: 1,
          yards: 5,
        },
        passing: {
          attempts: 11,
          completions: 2,
          cmp_pct: 18.182,
          yards: 8,
          avg_yards: 0.727,
          sacks: 1,
          sack_yards: 12,
          touchdowns: 0,
          longest: 9,
          interceptions: 0,
          rating: 24.29,
          longest_touchdown: 0,
          air_yards: 6,
          redzone_attempts: 0,
          gross_yards: 8,
          throw_aways: 0,
          poor_throws: 0,
          defended_passes: 0,
          dropped_passes: 0,
          spikes: 0,
          blitzes: 0,
          hurries: 0,
          knockdowns: 0,
          pocket_time: 0.0,
          avg_pocket_time: 0.0,
          net_yards: -4,
          batted_passes: 0,
          on_target_throws: 0,
        },
      },
      {
        id: "dbd256b0-99b8-11ec-86dc-ff0add1e628b",
        name: "Nicholas Falah",
        jersey: "74",
        position: "OL",
        games_played: 1,
        games_started: 1,
      },
      {
        id: "dfcd9ad0-99a5-11ec-a6e2-072ef8c4179b",
        name: "Ajene Harris",
        jersey: "0",
        position: "CB",
        games_played: 0,
        games_started: 0,
      },
      {
        id: "e0cd0ae0-c2a1-11ec-aadc-718b5de7779b",
        name: "Shakur Brown",
        jersey: "25",
        position: "CB",
        games_played: 1,
        games_started: 0,
        defense: {
          tackles: 0,
          assists: 1,
          combined: 1,
          sacks: 0.0,
          sack_yards: 0.0,
          interceptions: 0,
          passes_defended: 0,
          forced_fumbles: 0,
          fumble_recoveries: 0,
          qb_hits: 0,
          tloss: 0.0,
          tloss_yards: 0.0,
          safeties: 0,
          sp_tackles: 0,
          sp_assists: 1,
          sp_forced_fumbles: 0,
          sp_fumble_recoveries: 0,
          sp_blocks: 0,
          misc_tackles: 0,
          misc_assists: 0,
          misc_forced_fumbles: 0,
          misc_fumble_recoveries: 0,
          def_targets: 0,
          def_comps: 0,
          blitzes: 0,
          hurries: 0,
          knockdowns: 0,
          missed_tackles: 0,
          batted_passes: 0,
        },
      },
      {
        id: "e47fb0a0-a56b-11ec-b024-bdae402a3fdb",
        name: "Dale Warren",
        jersey: "45",
        position: "OLB",
        games_played: 2,
        games_started: 0,
        penalties: {
          penalties: 1,
          yards: 10,
        },
      },
      {
        id: "e4fba280-99a6-11ec-9588-2d3ae1c75954",
        name: "Bailey Gaither",
        jersey: "4",
        position: "WR",
        games_played: 2,
        games_started: 0,
        receiving: {
          receptions: 10,
          targets: 16,
          yards: 159,
          avg_yards: 15.9,
          longest: 37,
          touchdowns: 1,
          longest_touchdown: 37,
          yards_after_catch: 15,
          redzone_targets: 1,
          air_yards: 144,
          broken_tackles: 0,
          dropped_passes: 0,
          catchable_passes: 0,
          yards_after_contact: 0,
        },
        punt_returns: {
          returns: 0,
          yards: 0,
          avg_yards: 0.0,
          touchdowns: 0,
          longest: 0,
          faircatches: 1,
          longest_touchdown: 0,
        },
        defense: {
          tackles: 0,
          assists: 0,
          combined: 0,
          sacks: 0.0,
          sack_yards: 0.0,
          interceptions: 0,
          passes_defended: 0,
          forced_fumbles: 0,
          fumble_recoveries: 0,
          qb_hits: 0,
          tloss: 0.0,
          tloss_yards: 0.0,
          safeties: 0,
          sp_tackles: 2,
          sp_assists: 0,
          sp_forced_fumbles: 0,
          sp_fumble_recoveries: 0,
          sp_blocks: 0,
          misc_tackles: 0,
          misc_assists: 0,
          misc_forced_fumbles: 0,
          misc_fumble_recoveries: 0,
          def_targets: 0,
          def_comps: 0,
          blitzes: 0,
          hurries: 0,
          knockdowns: 0,
          missed_tackles: 0,
          batted_passes: 0,
        },
      },
      {
        id: "ed7c7040-c1cb-11ec-802e-a76c53ad718c",
        name: "Eli Walker",
        jersey: "3",
        position: "DB",
        games_played: 0,
        games_started: 0,
      },
      {
        id: "f946db60-99ba-11ec-86dc-ff0add1e628b",
        name: "Tyson Graham Jr.",
        jersey: "0",
        position: "OLB",
        games_played: 1,
        games_started: 1,
        defense: {
          tackles: 1,
          assists: 1,
          combined: 2,
          sacks: 0.0,
          sack_yards: 0.0,
          interceptions: 0,
          passes_defended: 0,
          forced_fumbles: 0,
          fumble_recoveries: 0,
          qb_hits: 0,
          tloss: 0.0,
          tloss_yards: 0.0,
          safeties: 0,
          sp_tackles: 0,
          sp_assists: 0,
          sp_forced_fumbles: 0,
          sp_fumble_recoveries: 0,
          sp_blocks: 0,
          misc_tackles: 0,
          misc_assists: 0,
          misc_forced_fumbles: 0,
          misc_fumble_recoveries: 0,
          def_targets: 0,
          def_comps: 0,
          blitzes: 0,
          hurries: 0,
          knockdowns: 0,
          missed_tackles: 0,
          batted_passes: 0,
        },
      },
      {
        id: "fc4ade80-99b8-11ec-86dc-ff0add1e628b",
        name: "Brayden Patton",
        jersey: "58",
        position: "OL",
        games_played: 2,
        games_started: 2,
      },
    ],
    _comment:
      "Generation started @ 2022-04-25 22:01:41 UTC ended @ 2022-04-25 22:01:41 UTC",
  };

  if (player) {
    let draft = <div>Draft not available</div>;
    if (player.draft) {
      draft = (
        <div>
          {console.log("here")}
          {console.log(stats)}
          <p className="player-data">Draft Round: {player.draft.round}</p>
        </div>
      );
    }
    return (
      <div className="player-dialog">
        <p className="player-name">{player.name}</p>
        <p className="player-data">{player.position}</p>
        <p className="player-data">{player.team}</p>
        <p className="player-data">{getAge(player.birth_date)}</p>

        <p className="player-data">{player.college}</p>
        <p className="player-data">{player.high_school}</p>
        <p className="player-data">#{player.jersey}</p>
        <p className="player-data">
          {Math.floor(player.height / 12)}'{player.height % 12}"
        </p>
        <p className="player-data">{player.weight}lb</p>
        <p className="player-data">{draft}</p>
      </div>
    );
  } else {
    return null;
  }
}

export default PlayerDialog;
