/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function City({ ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/city.glb");
  return (
    <group ref={group} {...props} dispose={null}>
      <group
        position={[-0.02, 1.11, 2.42]}
        rotation={[1.13, 0, 0]}
        scale={0.13}
      >
        <mesh
          geometry={nodes.Plane_1.geometry}
          material={materials["Material.003"]}
        />
        <mesh
          geometry={nodes.Plane_2.geometry}
          material={materials["Material.004"]}
        />
      </group>
      <group position={[0.33, 1.14, 2.28]} rotation={[1.11, 0, 0]} scale={0.15}>
        <mesh
          geometry={nodes.Plane006_1.geometry}
          material={materials["Material.003"]}
        />
        <mesh
          geometry={nodes.Plane006_2.geometry}
          material={materials["Material.004"]}
        />
      </group>
      <group
        position={[-0.18, 1.37, 2.1]}
        rotation={[0.96, 0, 0]}
        scale={[0.15, 0.32, 0.15]}
      >
        <mesh
          geometry={nodes.Plane007_1.geometry}
          material={materials["Material.003"]}
        />
        <mesh
          geometry={nodes.Plane007_2.geometry}
          material={materials["Material.004"]}
        />
      </group>
      <group
        position={[0.26, 1.26, 1.7]}
        rotation={[0.65, 0, 0]}
        scale={[0.15, 0.32, 0.15]}
      >
        <mesh
          geometry={nodes.Plane008.geometry}
          material={materials["Material.003"]}
        />
        <mesh
          geometry={nodes.Plane008_1.geometry}
          material={materials["Material.004"]}
        />
      </group>
      <group position={[-0.5, 1.3, 2.22]} rotation={[1.02, 0, 0]} scale={0.15}>
        <mesh
          geometry={nodes.Plane009.geometry}
          material={materials["Material.003"]}
        />
        <mesh
          geometry={nodes.Plane009_1.geometry}
          material={materials["Material.004"]}
        />
      </group>
      <group
        position={[-0.36, 1.05, 2.46]}
        rotation={[1.04, 0, 0]}
        scale={0.13}
      >
        <mesh
          geometry={nodes.Plane010.geometry}
          material={materials["Material.003"]}
        />
        <mesh
          geometry={nodes.Plane010_1.geometry}
          material={materials["Material.004"]}
        />
      </group>
      <group position={[-0.4, 1.74, 2.01]} rotation={[0.88, 0, 0]} scale={0.13}>
        <mesh
          geometry={nodes.Plane011.geometry}
          material={materials["Material.003"]}
        />
        <mesh
          geometry={nodes.Plane011_1.geometry}
          material={materials["Material.004"]}
        />
      </group>
      <group position={[-0.17, 1.8, 1.88]} rotation={[0.67, 0, 0]} scale={0.13}>
        <mesh
          geometry={nodes.Plane012.geometry}
          material={materials["Material.003"]}
        />
        <mesh
          geometry={nodes.Plane012_1.geometry}
          material={materials["Material.004"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/city.glb");
