/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useEffect } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export default function Model({ ...props }) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/usflworld.glb");
  const { actions } = useAnimations(animations, group);
  useEffect(() => {
    actions.EmptyAction.play();
    actions["SphereAction.001"].play();
  });
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Empty">
          <mesh
            name="Sphere"
            geometry={nodes.Sphere.geometry}
            material={materials["Material.002"]}
            position={[0, 4.45, 0]}
            rotation={[Math.PI, -1.48, Math.PI]}
            scale={[0.05, 0.05, 0.1]}
          />
        </group>
        <mesh
          name="Circle"
          geometry={nodes.Circle.geometry}
          material={materials["Material.001"]}
          position={[0, 2.58, 0]}
          scale={[0.05, 0.1, 0.05]}
        />
        <group name="Icosphere">
          <mesh
            name="Icosphere002"
            geometry={nodes.Icosphere002.geometry}
            material={materials["Material.002"]}
          />
          <mesh
            name="Icosphere002_1"
            geometry={nodes.Icosphere002_1.geometry}
            material={materials["Material.003"]}
          />
          <mesh
            name="Icosphere002_2"
            geometry={nodes.Icosphere002_2.geometry}
            material={materials.Material}
          />
        </group>
        <group
          name="Plane"
          position={[-0.02, 1.11, 2.42]}
          rotation={[1.13, 0, 0]}
          scale={0.13}
        >
          <mesh
            name="Plane_1"
            geometry={nodes.Plane_1.geometry}
            material={materials["Material.003"]}
          />
          <mesh
            name="Plane_2"
            geometry={nodes.Plane_2.geometry}
            material={materials["Material.004"]}
          />
        </group>
        <group
          name="Plane001"
          position={[0.33, 1.14, 2.28]}
          rotation={[1.11, 0, 0]}
          scale={0.15}
        >
          <mesh
            name="Plane006_1"
            geometry={nodes.Plane006_1.geometry}
            material={materials["Material.003"]}
          />
          <mesh
            name="Plane006_2"
            geometry={nodes.Plane006_2.geometry}
            material={materials["Material.004"]}
          />
        </group>
        <group
          name="Plane002"
          position={[-0.18, 1.37, 2.1]}
          rotation={[0.96, 0, 0]}
          scale={[0.15, 0.32, 0.15]}
        >
          <mesh
            name="Plane007_1"
            geometry={nodes.Plane007_1.geometry}
            material={materials["Material.003"]}
          />
          <mesh
            name="Plane007_2"
            geometry={nodes.Plane007_2.geometry}
            material={materials["Material.004"]}
          />
        </group>
        <group
          name="Plane003"
          position={[0.26, 1.26, 1.7]}
          rotation={[0.65, 0, 0]}
          scale={[0.15, 0.32, 0.15]}
        >
          <mesh
            name="Plane008"
            geometry={nodes.Plane008.geometry}
            material={materials["Material.003"]}
          />
          <mesh
            name="Plane008_1"
            geometry={nodes.Plane008_1.geometry}
            material={materials["Material.004"]}
          />
        </group>
        <group
          name="Plane004"
          position={[-0.5, 1.3, 2.22]}
          rotation={[1.02, 0, 0]}
          scale={0.15}
        >
          <mesh
            name="Plane009"
            geometry={nodes.Plane009.geometry}
            material={materials["Material.003"]}
          />
          <mesh
            name="Plane009_1"
            geometry={nodes.Plane009_1.geometry}
            material={materials["Material.004"]}
          />
        </group>
        <group
          name="Plane005"
          position={[-0.36, 1.05, 2.46]}
          rotation={[1.04, 0, 0]}
          scale={0.13}
        >
          <mesh
            name="Plane010"
            geometry={nodes.Plane010.geometry}
            material={materials["Material.003"]}
          />
          <mesh
            name="Plane010_1"
            geometry={nodes.Plane010_1.geometry}
            material={materials["Material.004"]}
          />
        </group>
        <group
          name="Plane006"
          position={[-0.4, 1.74, 2.01]}
          rotation={[0.88, 0, 0]}
          scale={0.13}
        >
          <mesh
            name="Plane011"
            geometry={nodes.Plane011.geometry}
            material={materials["Material.003"]}
          />
          <mesh
            name="Plane011_1"
            geometry={nodes.Plane011_1.geometry}
            material={materials["Material.004"]}
          />
        </group>
        <group
          name="Plane007"
          position={[-0.17, 1.8, 1.88]}
          rotation={[0.67, 0, 0]}
          scale={0.13}
        >
          <mesh
            name="Plane012"
            geometry={nodes.Plane012.geometry}
            material={materials["Material.003"]}
          />
          <mesh
            name="Plane012_1"
            geometry={nodes.Plane012_1.geometry}
            material={materials["Material.004"]}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/usflworld.glb");
